### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by john-darwin** [SergioTallo/Multivariate_Time_Series_Prediction_Transformers#1]
Nice job!!!
I am a Chinese guy with a lot of desire to learn more about Transformer and time series prediction. 
Data sources are important to my new professional direction ，and I would like to know how did you get this dataset? Is it a dataset published by a website?

**Comment by SergioTallo** [comment]
Hi!
First of all, thank you! I am quite new in the field and hearing good things is always something very encouraging!
The dataset. No, I receive this dataset from my thesis supervisor. They are electrical factory from an unknown factory. Well, unknown for me. The factory is real. But, is quite irrelevant for the thesis where the dataset came from, that is the main reason for not mention it.

**Comment by john-darwin** [comment]
> reopened this [昨天](#event-6798639382)

Thank you for your reply, wish you all the best in life and work~
